name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: chromium
        path: |
          base/**
          build/**
